language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "node"
  - lts/*
  - 12
  - 10
  - 8
cache:
  directories:
    - "$HOME/.npm"

after_success: 
  - npm run coverage

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: npm release
      node_js: lts/*
      script: npm run build
      deploy:
        provider: npm
        email: doni.seferi@gmail.com
        api_key: $NPM_TOKEN
        edge: true
        skip_cleanup: true
        on:
          tags: true
          branch: master