language: node_js
os: linux
node_js:
  - "lts/*"
jobs:
  include:
    - stage: testing
      after_success:
        - npm run coverage
    - stage: npm release
      before_deploy:
      - npm run build
      deploy:
        provider: npm
        email: doni.seferi@gmail.com
        api_token: $NPM_TOKEN
        cleanup: true
        edge: true
        access: public
        on: 
          branch: master
          tags: true
